# Generated by Django 5.1.1 on 2024-11-04 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id_eixo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_eixo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id_especialidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id_gerencia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_objetivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id_prioridade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_prioridade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nome_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_cargo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.cargo')),
                ('id_gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.gerencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('processo_sei', models.CharField(max_length=255)),
                ('observacoes', models.CharField(max_length=255)),
                ('id_eixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.eixo')),
                ('id_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('id_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.projeto')),
            ],
            options={
                'unique_together': {('id_projeto', 'id_colaborador')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tarefa', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.CharField(max_length=255)),
                ('id_prioridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.prioridade')),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.projeto')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.status')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe_Tarefa',
            fields=[
                ('id_equipe_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('id_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_equipes', to='central_de_projetos.equipe')),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_equipes', to='central_de_projetos.equipe')),
                ('id_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.tarefas')),
            ],
        ),
        migrations.CreateModel(
            name='Documento_tarefa',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='uploads/tarefas')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('id_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_de_projetos.tarefas')),
            ],
        ),
    ]
