# Generated by Django 5.0.7 on 2024-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_de_projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipe_tarefa',
            constraint=models.UniqueConstraint(fields=('id_tarefa', 'id_projeto', 'id_colaborador'), name='unique_equipe_tarefa'),
        ),
    ]
