# Generated by Django 5.1.2 on 2024-11-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_de_projetos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='progresso',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
