# Generated by Django 5.0.7 on 2024-11-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_de_projetos', '0002_equipe_tarefa_unique_equipe_tarefa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='equipe',
            constraint=models.UniqueConstraint(fields=('id_projeto', 'id_colaborador'), name='unique_projeto_colaborador'),
        ),
    ]
